### ISSUE TITLE
Sending messages doesn't work with current beta of companion

### ISSUE THREAD

**Issue by robertskiba** [bitfocus/companion-module-binwiederhier-ntfy#6]
Hi!

I just tested the NTFY module in current companion [v3.5.0+7643-main-74373f23] beta and it doesn't work anymore. 

I didn't use it for some time so I'm not sure if it works with the current 3.4.3 version, but the following error shows up in the logs:

` Instance/Wrapper/ntfy: Error executing action: n.tags.join is not a function`

**Comment by josephdadams** [comment]
If the message tags/emojis are blank or you have more than 1, it will work. I will fix it for instances of just one emoji.

**Comment by josephdadams** [comment]
fixed in `v1.0.1` of the module
